version: 1.1
python_job:
  job_type: BASH_COMMAND_RUNNER
  mode: python
  image: auto-select
  include_local_dir: true
  custom_file_filter:
  - '*.md'
  dependencies: requirements.txt
  commands:
    - "tune download meta-llama/Meta-Llama-3-8B-Instruct --hf-token '<your hugging face token>' "
    - tune run lora_finetune_single_device --config llama3/8B_lora_single_device


