version: 1.0
python_job:
  workspace_dir: .
  image: robbie:1.0.0-gpu-py3.12-torch2.5-ubuntu22.04-alpha
  environment_id:
  commands:
  - pip install -r requirements.txt
  - "tune download meta-llama/Meta-Llama-3-8B-Instruct --output-dir /tmp/Meta-Llama-3-8B-Instruct --hf-token '<your hugging face token>' "
  - tune run lora_finetune_single_device --config llama3/8B_lora_single_device

