version: 1.1
python_job:
  job_type: BASH_COMMAND_RUNNER
  mode: python
  funding_group_id: cecfc347-5680-4fb0-ae99-b029941b08dd
  environment_id: 52dbdaa5-eb8e-4a3d-9745-77db52b91b34
  image: auto-select
  include_local_dir: true
  dependencies: requirements.txt
