version: 1.1
python_job:
  job_type: BASH_COMMAND_RUNNER
  mode: python
  rpv: '3.12'
  environment_id: e4e3f767-392b-4b4a-9a67-1b8807c3706c
  image: auto-select
  include_local_dir: true
  custom_file_filter:
  - '*.md'
  dependencies: none
  commands:
  - python main.py --save-model
