version: 1.1
python_job:
  job_type: BASH_COMMAND_RUNNER
  mode: python
  image: auto-select
  include_local_dir: true
  custom_file_filter:
  - '*.md'
  dependencies: none
  commands:
  - python main.py --cuda --epochs 6
